### ISSUE TITLE
No module named 'converter'

### ISSUE THREAD

**Issue by HughSalvatore** [AumitLeon/markdown_html_converter#27]
Os: windows 10/64
Python: 3.7/64
Issue Description:
When I run command 'md-to-html -i ***.md -o ***.html' by 'cmd', It prompted me with an error "ModuleNotFoundError: No module named 'converter'". I have reinstalled this module many times by 'pip', but it doesn't work. I think this module is very convenient for me, and I also would like to contribute back to it.

**Comment by jaxxor44** [comment]
Dito.
Windows 10 64bit
Python 3.7
Description:
any attempted usage of md-to-html in any context produces the:
Module not found error: no module named 'converter'.

**Comment by yeroc-sebrof** [comment]
If you're just using the pip version then there is a converter.py in the src folder of the git cloned version that it's prob just missing. I had the same problem with the pip version too tho

**Comment by AumitLeon** [comment]
Hi guys! Thanks for using my module. I apologize for being inactive with this thread and general updates -- I made this project during the summer between semesters and just lost track of it with school and work in the way. The error you guys are seeing is a result of the module being written as a python 2 module, and you guys are attempting to use it in python 3 environments. 

A quick work around would be to use a virtual environment with python 2: 
```
virtualenv --python={path-to-python2} {env-name}
source {env-name}/bin/activate
pip install md-to-html
```
Replace `{path-to-python2}` with the path to your python2 installation (might need to install python2 if you don't have one). Replace {env-name} with whatever you'd like to name the environment. 

After running the above steps, you should be able to run:
```
md-to-html -i *.md -o *.html'
```
This is just for the time being. I realize it's not ideal to have this module as a python 2 module given the scheduled [retirement of python 2](https://pythonclock.org/). I will create a series of issues that catalog the work necessary to get the module python 3 compatible, as well as additional functionality and refactoring work that is needed.

Any and all contributions welcome -- please checkout the [contributing](https://github.com/AumitLeon/markdown_html_converter/blob/master/CONTRIBUTING.md) guidelines if you are interested!

**Comment by AumitLeon** [comment]
Hi all -- quick update, #37 should have resolved the above issues.
