### ISSUE TITLE
'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by dev-brutus** [AumitLeon/markdown_html_converter#60]
I try co convert my md document to hml and I had this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/md-to-html", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/src/converter.py", line 26, in main
    html_doc = open(args.output, "w", encoding="utf-8")
TypeError: 'encoding' is an invalid keyword argument for this function
```
I have Python 2.7.17 on Ubunti 18.04.1

Application was installed with pip:
`sudo pip install md-to-html`

Application was run from command line:
`md-to-html --input 01-решения.md`

**Comment by ManuelAudibene** [comment]
same for me - using debian latest and python

**Comment by AumitLeon** [comment]
Hi there,

It looks like `encoding` was added as an argument to the `open` function in python 3, so unfortunately, you'll need to use python 3 to use this module. I would recommend using a virtual environment to manage python versions and packages (something like [pyenv](https://github.com/pyenv/pyenv) and [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv).
